name: Build Windows

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version number"
        type: string

  workflow_call:
    inputs:
      version:
        description: "The version number"
        type: string
    outputs:
      artifact:
        description: "The artifact that was built"
        value: ${{ jobs.build-windows.outputs.artifact }}

jobs:
  build-windows:
    runs-on: windows-2022
    env:
      CHRISTIAN_VERSION: ${{ inputs.version }}
    outputs:
      artifact: ${{ steps.uploaded.outputs.artifact }}
    steps:
      # https://github.com/actions/checkout
      - name: checkout source
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      # https://stackoverflow.com/questions/5879076/how-to-create-a-batch-file-for-visual-studio-command-prompt
      - name: build
        run: |
          call "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvarsall.bat" x86_amd64
          cmake --preset windows-x64-debug
          cmake --build --preset windows-x64-debug
          cpack -G WIX --config out/build/windows-x64-debug/CPackConfig.cmake
          mkdir Windows
          copy out\\build\\windows-x64-debug\\ChristiansSteamBot.exe Windows
          copy ChristiansSteamBot*.msi Windows
        shell: cmd
      # https://github.com/actions/upload-artifact
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: Windows
          overwrite: true
      - name: produce outputs
        id: uploaded
        run: echo "artifact=Windows" >> $GITHUB_OUTPUT
