name: Build Linux

on:
  workflow_call:
    outputs:
      artifact:
        description: "The artifact that was built"
        value: ${{ jobs.build-linux.outputs.artifact }}

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    outputs:
      artifact: ${{ steps.uploaded.outputs.artifact }}
    steps:
      - name: install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev
          sudo apt-get install -y libprotobuf-dev protobuf-compiler
          sudo apt-get install -y libsystemd-dev libzstd-dev libbz2-dev liblzma-dev
      # https://github.com/actions/checkout
      - name: checkout source
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: build
        run: |
          export CHRISTIAN_VERSION="${{github.ref_name}}"
          cmake -S . -B build/Debug -D CMAKE_BUILD_TYPE=Debug
          cmake --build build/Debug
          cpack -G DEB --config build/Debug/CPackConfig.cmake
          mkdir Linux
          mv christianssteambot*.deb Linux/
      # https://github.com/actions/upload-artifact
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux-x64
          path: Linux
          overwrite: true
      - name: produce outputs
        id: uploaded
        run: echo "artifact=Linux-x64" >> $GITHUB_OUTPUT
