name: Build Windows
on: [workflow_dispatch]
jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      # https://stackoverflow.com/questions/5879076/how-to-create-a-batch-file-for-visual-studio-command-prompt
      - run: call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: cmake --preset windows-x64-debug
      - run: cmake --build --preset windows-x64-debug
      # https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@v4
        with:
          name: ChristiansSteamBot-Windows.exe
          path: out\build\windows-x64-debug\ChristiansSteamBot.exe
          overwrite: true
