name: Build a dummy package

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version number"
        type: string

  workflow_call:
    inputs:
      version:
        description: "The version number"
        type: string
    outputs:
      artifact:
        description: "The artifact that was built"
        value: ${{ jobs.build-dummy.outputs.artifact }}

jobs:
  build-dummy:
    env:
      CHRISTIAN_VERSION: ${{ inputs.version }}

    runs-on: ubuntu-24.04
    outputs:
      artifact: ${{ steps.uploaded.outputs.artifact }}
    steps:
      - name: build
        run: |
          echo "Version: $CHRISTIAN_VERSION"
          mkdir Dummy
          echo "This is just a dummy 'package' \#1 for development" > Dummy/Dummy-1.txt
          echo "This is just a dummy 'package' \#2 for development" > Dummy/Dummy-2.txt
      # https://github.com/actions/upload-artifact
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dummy
          path: Dummy
          overwrite: true
          retention-days: 1
      - name: produce outputs
        id: uploaded
        run: echo "artifact=Dummy" >> $GITHUB_OUTPUT
